### ISSUE TITLE
[Suggestion] Remove the Interface suffix in interface names

### ISSUE THREAD

**Issue by stof** [broadway/broadway#12]
See http://verraes.net/2013/09/sensible-interfaces/ for the argumentation. Note that most components are already using a descriptive name for the provided implementation rather than making it the priviledged one (for instance `class SimpleEventBus implements EventBusInterface`)

Doing such should be done quickly, to avoid fighting with BC concerns with the current interface names.

**Comment by remi-san** [comment]
Hey everyone,

Has this been burried? Can we brint it back to life? as there seemed to be a consensus on approch number 4...

If so, tell me, I'd be happy to help and submit a PR on that matter.

**Comment by wjzijderveld** [comment]
Not buried, but a bit low on prio.

To be honest, I'm not sure what the best approach is here. 
I'm afraid that if change all at the same time, the discussions are going to take forever :smile:

**Comment by unkind** [comment]
It would be great to drop the suffix.

**Comment by unkind** [comment]
> Not buried, but a bit low on prio.
Sorry for bumping it again, but wouldn't it be too late to rename interfaces later? This is a hard BC break.

**Comment by othillo** [comment]
we are about to tag 1.0, so I guess it's now or never time for this change. 

Does anyone want to create a PR? It would be highly appreciated.

If not we should bury this as a known issue. :expressionless:

**Comment by unkind** [comment]
@othillo I can try it. However, it makes sense to make decision regarding the following classes as they conflict with corresponding interfaces:
* `class CommandSerializer` -> `NaiveCommandSerializer`
* `class EventDispatcher` -> `InMemoryEventDispatcher`
* `class DomainEventStream` -> `ArrayDomainEventStream`
* `class CommandHandler` -> ?
* `class Projector` -> ?
* `class EventSourcedEntity` -> ?
* `class CommandHandler` -> ?

Do you really need `CommandHandlerInterface`, `ProjectorInterface`, `EventSourcedEntityInterface`,  `CommandHandlerInterface`? The simplest solution would be just to remove them in favor of existing concrete classes. It is not that terrible as this convention probably reveals useless contracts.

**Comment by othillo** [comment]
- [ ] Broadway/Auditing/CommandSerializerInterface -> ?
- [ ] Broadway/CommandHandling/CommandBusInterface -> ?
- [ ] Broadway/CommandHandling/CommandHandlerInterface -> ?
- [ ] Broadway/Domain/DomainEventStreamInterface -> ?
- [ ] Broadway/EventDispatcher/EventDispatcherInterface -> ?
- [ ] Broadway/EventHandling/EventBusInterface -> ?
- [ ] Broadway/EventHandling/EventListenerInterface -> ?
- [ ] Broadway/EventSourcing/AggregateFactory/AggregateFactoryInterface -> ?
- [ ] Broadway/EventSourcing/EventSourcedEntityInterface -> ?
- [ ] Broadway/EventSourcing/EventStreamDecoratorInterface -> ?
- [ ] Broadway/EventSourcing/MetadataEnrichment/MetadataEnricherInterface -> ?
- [ ] Broadway/EventStore/EventStoreInterface -> ?
- [ ] Broadway/EventStore/EventVisitorInterface -> ?
- [ ] Broadway/EventStore/Management/EventStoreManagementInterface -> ?
- [ ] Broadway/ReadModel/ProjectorInterface -> ?
- [ ] Broadway/ReadModel/ReadModelInterface -> ?
- [ ] Broadway/ReadModel/RepositoryFactoryInterface -> ?
- [ ] Broadway/ReadModel/RepositoryInterface -> ?
- [ ] Broadway/ReadModel/SerializableReadModelInterface -> ?
- [ ] Broadway/ReadModel/TransferableInterface -> ?
- [ ] Broadway/Repository/RepositoryInterface -> ?
- [ ] Broadway/Serializer/SerializableInterface -> ?
- [ ] Broadway/Serializer/SerializerInterface -> ?
