### ISSUE TITLE
[RFC] Symfony configurations for the aggregate factories and event repository

### ISSUE THREAD

**Issue by mbadolato** [broadway/broadway#121]
In my test project, I created the following `broadway.*` service definitions (the first 3 listed) to allow me to easily configure a repository (4th service definition below) to pass into my command handler (5th definition below).

Any interest in me submitting that back to the Symfony bundle configs?

I put the `broadway.aggregate_factory.named` in as an example but haven't used it yet. It could use a little more fleshing out to allow for overriding the constructor name argument, but it's minimal effort to do so and I can add it into the PR.

I'd only be submitting back the `broadway.*` definitions and can include docs showing how I use them, like the example here.

``` xml
<?xml version="1.0" encoding="UTF-8" ?>

<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <services>
        <service id="broadway.aggregate_factory.public" class="Broadway\EventSourcing\AggregateFactory\PublicConstructorAggregateFactory" public="false" />
        <service id="broadway.aggregate_factory.named" class="Broadway\EventSourcing\AggregateFactory\NamedConstructorAggregateFactory" public="false">
            <argument>instantiateForReconstitution</argument>
        </service>

        <service id="broadway.event_repository.public_constructor" class="Broadway\EventSourcing\EventSourcingRepository" abstract="true">
            <argument type="service" id="broadway.event_store" />
            <argument type="service" id="broadway.event_handling.event_bus" />
            <argument /> <!-- Argument #3 to be replaced in child definitions -->
            <argument type="service" id="broadway.aggregate_factory.public" />
        </service>

        <service id="cybernox.event_repository.client_management.client" parent="broadway.event_repository.public_constructor" public="false">
            <argument index="2">Cybernox\ClientManagement\Model\Client</argument>
        </service>

        <service id="cybernox.command_handler.client_manager.client" class="Cybernox\ClientManagement\CommandHandler\ClientCommandHandler" public="false">
            <argument type="service" id="cybernox.event_repository.client_management.client" />
            <tag name="command_handler" />
        </service>
    </services>
</container>
```

**Comment by asm89** [comment]
Seems interesting to me. If you don't use the they aren't in the way I guess.

ping @qandidate-labs/broadway

**Comment by cordoval** [comment]
:+1:

**Comment by wjzijderveld** [comment]
I'm fine with the first 2.

But I'm not sure about the third one yet, does it add that much value? Wouldn't most people still override that one because they have there own decorators?
I'm a bit afraid that there are to many exceptions on this convenience service and want to avoid clutter in our default services.

But definitely would like to see a PR of it :smile:

**Comment by wjzijderveld** [comment]
@mbadolato any update on this?

**Comment by mbadolato** [comment]
@wjzijderveld Totally forgot about this. I'll take a look at it sometime this week

**Comment by othillo** [comment]
@mbadolato I'm closing this for now. A PR is always welcome!
