### ISSUE TITLE
RFC Improve scenario test case API with constrained assertions

### ISSUE THREAD

**Issue by real34** [broadway/broadway#140]
The current Scenario implementations for test cases contains a `then` method asserting that the whole repository content equals the expected values.

When testing a ReadModel we've found it was a bit tedious to setup correct data for the `then` part of the scenario, and it damages test readability. We came up with the method below allowing us to only express constraints for each repository entry:

```
protected function thenAssertThat($constraints)
    {
        $valuesAndAssertions = new \MultipleIterator(\MultipleIterator::MIT_NEED_ANY);
        $valuesAndAssertions->attachIterator(new \ArrayIterator($this->repository->findAll()));
        $valuesAndAssertions->attachIterator(new \ArrayIterator($constraints));

        foreach ($valuesAndAssertions as $toAssert) {
            list($value, $hasConstraint) = $toAssert;
            $this->assertThat($value, $hasConstraint);
        }
    }
```

Usage:

```
$this->scenario
            ->given([
                $this->uneFicheIndicationCree(),
                new FicheIndicationEnvoyee($this->unIdIndication, $destinataireInitialId)
            ])
            ->when(
                new FicheIndicationTransmise($this->unIdIndication, $destinataireFinalId, '')
            )
            ->thenAssertThat([
               $this->attributeEqualTo('statut', Indication::STATUT_ENVOYEE)
           ]);
```

We can do a PR for bringing this API into Scenario test cases, but I wanted first to discuss the API you would prefer. So far I see 2 solutions:
- creating a separate method like shown above
- change the current `then` implementation to default to an `equalTo` constraint if the expectation row is not a constraint (for a _kind of_ backwards compatibility - only the assertions count would be increased)

What are yourt thoughts about it?

**Comment by mbadolato** [comment]
I definitely like the idea of improving the scenario testing for read models. I found them a bit cumbersome as well (see [here](https://github.com/qandidate-labs/broadway/issues/77)). I didn't read your solution in depth because of time right now, but will be interested in reading it later!

**Comment by wjzijderveld** [comment]
I can see how this can be very helpful. 

Just to make sure I understand how you use Broadway: You have an event that triggers the update of multiple read models (where you updated a single property)? And (in above example) you want to assert for all read models just the state of a single property?

I'm not really familiar with `MultipleIterator`, is it correct that you would need the same amount of asserts as there are read models? I guess that your example has a possible fatal error when you run out of constraints but have read models left?

But I would be in favor of this change and in my opinion it can be implemented in the current `then` methods. Like you said, we can map to `equalTo` when a values is not a constraint.

**Comment by othillo** [comment]
I'm closing this for now. A PR is more than welcome!
