### ISSUE TITLE
Look at the ReadModelTestCase

### ISSUE THREAD

**Issue by wjzijderveld** [broadway/broadway#172]
It's name indicates that it applies all read models, while it actually requires you to implement Serializable.
Maybe rename it to `SerializableReadModelTestCase`?

**Comment by matthiasnoback** [comment]
I noticed the same thing, in my case I was testing the |serializability" of my domain events, but there is a test case for that as well: `SerializableEventTestCase`. Still, a more general test case would be quite useful.
