### ISSUE TITLE
Saga readme needs more emphasis on consistency responsibilities

### ISSUE THREAD

**Issue by Xerkus** [broadway/broadway#195]
Saga readme does not put enough emphasis on the fact that saga is a transactional mechanism responsible for consistent state in both successful and failed process flows. It is responsible for rolling back or compensating state changes happened as part of it.

On a purist side note: readme states that saga can be seen as process manager but i personally believe those two are separate but strongly related concepts. They differ in conceptual goal where saga putting emphasis on consistency and failure compensation while process manager on the flow needed to achieve goal.

**Comment by othillo** [comment]
@Xerkus do you mind creating a PR on https://github.com/broadway/broadway-saga to improve the README?

I'm closing this for now.
