### ISSUE TITLE
CommandBus/EventBus should clear the queue on failure

### ISSUE THREAD

**Issue by asm89** [broadway/broadway#199]
Currently the command bus and event bus implementation shipped with broadway will always end up in a state where you can dispatch a new message. If you do that, the queue that was still there at the time of the exception will be handled. I think we should clear the queue if there is an exception.

Possibly we could:
- clear the queue
- wrap the original exception in a `Dispatch`/`PublishException` and put the remaining commands/events on there

The latter will be a breaking change though.

**Comment by asm89** [comment]
@wjzijderveld @othillo Any thoughts? We should probably ping some other folks as well.

cc @tPl0ch @kimlai Who committed the code that made it possible to keep using the command and event bus after an exception.

**Comment by tPl0ch** [comment]
@asm89 That was @kimlai I think, I just added the test case for that (if I recall correctly)

**Comment by asm89** [comment]
@tPl0ch https://github.com/qandidate-labs/broadway/commit/d6f61639f0e1b5c1df02ec4492493abb3f9cef88 ;) 

Mostly want to figure out if someone is really against draining the queue. The second question is wrapping the exception which might be a more annoying change for folks.

**Comment by asm89** [comment]
And ack at that you just added the test case, but because you finished the work I reckoned you and @kimlai care about this.

**Comment by kimlai** [comment]
Hi @asm89 

I have to admit that I never thought about that... I'll need to check the use cases where I want to recover from an exception and continue dispatching events, but I don't think that I have anything against clearing the queue (not clearing it might actually be the cause of some weird behaviour that I've been seeing but didn't take the time to investigate). 

Thanks for the eye-opener, I'll check this asap.

**Comment by wjzijderveld** [comment]
I think clearing the queue makes sense. There is no way to tell if the commands in the queue are still valid.
Not sure yet about how to handle the _leftover_ commands. Having a way to inspect the leftover commands might be nice. But maybe that is more a job for the [EventDispatchingCommandBus](https://github.com/qandidate-labs/broadway/blob/master/src/Broadway/CommandHandling/EventDispatchingCommandBus.php)?

**Comment by tPl0ch** [comment]
@wjzijderveld I had exactly the same idea on the weekend. We could pass the incomplete command stack within the event. In the handlers there could be custom logic to handle these commands (retry strategy, logging, etc.)

**Comment by tPl0ch** [comment]
See https://github.com/qandidate-labs/broadway/pull/201
