### ISSUE TITLE
DateTime does not use microseconds in comparison

### ISSUE THREAD

**Issue by dbellettini** [broadway/broadway#203]
See https://github.com/dbellettini/broadway/commit/705a7773f712f4ea1fdb7c6be79951c1547becdb

**Comment by wjzijderveld** [comment]
FYI: I found the issue in PHP itself and fixed that: https://github.com/php/php-src/pull/1653

It should be released in 5.6.19 and 7.0.4 (I think), but we probably still want to fix it in Broadway to fix it for the older versions.
