### ISSUE TITLE
Varchar for DBAL type column?

### ISSUE THREAD

**Issue by Richtermeister** [broadway/broadway#212]
Currently the DBALEventStore configures the type field as "text" which results in the Longtext mysql type, which can't be indexed. Is there a particular reason for this, or can we switch this to string and add an index?

https://github.com/qandidate-labs/broadway/blob/master/src/Broadway/EventStore/DBALEventStore.php#L173

**Comment by mbadolato** [comment]
Perhaps they did it to not limit the full path of the event class that is used in the type field from being restricted to 255 characters?

**Comment by mdwheele** [comment]
I don't believe the intent was to use that column as part of a compound key <type, uuid> as there is currently a PR to split the stream namespace. That would leave type remaining as a seemingly convenience field for reporting perhaps. 

Seems that the current expectation is that you know the aggregate class at time of repository construction and query the event store by aggregate identifier, leaving clients technically able to play events from one aggregate type into another. Something would have to be horribly wrong to do this but...

I treat identity in the store as a "stream identifier" and simply concatenate aggregate fqdn to its uuid to form the stream identifier. I use a slightly modified table schema and also guard against excessively long fqdns. It looks like the current PR is headed towards explicating this concept of "namespaces identity" of streams.
