### ISSUE TITLE
Allow to get a native (PHP builtin) DateTime from a Broadway\Domain\DateTime object

### ISSUE THREAD

**Issue by cyberwolf** [broadway/broadway#216]
Currently it's difficult to perform various operations (like formatting the date/time in a specific way) with Broadway's DateTime implementation, because you can not easily get a native (PHP builtin) \DateTime object from it and Broadway's DateTime features are rather limited.

Therefore it would be handy to add a new toNative() method, which returns a native \DateTime object.

What we currently use as a workaround wherever we need a native DateTime object:

``` php
// $date is a Broadway\Domain\DateTime object
\DateTime::createFromFormat(
            DateTime::FORMAT_STRING,
            $date->toString()
        );
```

**Comment by macintoshplus** [comment]
:+1:

**Comment by Konafets** [comment]
Or use [Carbon](http://carbon.nesbot.com/) for date handling
