### ISSUE TITLE
Querying the event store by date

### ISSUE THREAD

**Issue by Miliooo** [broadway/broadway#219]
The event store stores the date and time in the field recorded_on.
But it uses a varchar for this (not a dateTime) for example  '2015-10-24T06:20:11.434118+00:00' (Y-m-d\TH:i:s.uP)

If I wanted to query the event store for all events that happened after a specific date, how would I archieve this?

**Comment by othillo** [comment]
I'm closing this. Did you find a solution for your problem, @Miliooo ?

**Comment by mhightower** [comment]
I'm getting into the same issue and since I'm implementing CQRS I'm leaving querying on the Read side. You would need to a to Create a ReadModel (with a Projector to keep the ReadModel up to date) that is able to answer that question.
