### ISSUE TITLE
Identity - Logo

### ISSUE THREAD

**Issue by henrikbjorn** [broadway/broadway#24]
It seems like its all the rage currently to have a logo, and lets be honest logos are fun :)

I suggest something like one of theese https://www.google.dk/search?q=broadway&es_sm=91&source=lnms&tbm=isch&sa=X&ei=XeL-U8CKLsi00QX-94D4Aw&ved=0CAgQ_AUoAQ&biw=1916&bih=979#q=broadway+street+sign&tbm=isch&imgdii=_

id even go so far an pay someone if people are up for this :)

**Comment by cordoval** [comment]
can i attempt something?

**Comment by henrikbjorn** [comment]
@cordoval i am sure nobody would mind :)

**Comment by cordoval** [comment]
he he ok i will see if i can pull something up this week/+end

**Comment by noetix** [comment]
:+1: 

This is really needed ASAP :smiley:

**Comment by NoelDavies** [comment]
What happened with this logo? 😄
