### ISSUE TITLE
Linked Processors when using a custom Event Bus

### ISSUE THREAD

**Issue by aleixverges** [broadway/broadway#251]
Hi,
    Is there any particular way to add event processors to custom event buses. Note that I'm not using the SimpleEventBus comming from Broadway but a different bus with some custom functionality

Thanks

**Comment by wjzijderveld** [comment]
The easiest way would be to alias your event bus as `broadway.event_handling.event_bus`, then it should register.

The other option would be to register a ComoilerPass that does this. See the [BroadwayBundle](https://github.com/qandidate-labs/broadway/blob/master/src/Broadway/Bundle/BroadwayBundle/BroadwayBundle.php).

**Comment by aleixverges** [comment]
Thank you so much!
