### ISSUE TITLE
Close the connection after loading aggregate

### ISSUE THREAD

**Issue by Konafets** [broadway/broadway#256]
I am using the Broadcast/Laravel connector from @nWidart. The package provides a replay command which utilizes the `load($id)` method of [Broadway/EventStore/DBALEventStore.php](https://github.com/qandidate-labs/broadway/blob/master/src%2FBroadway%2FEventStore%2FDBALEventStore.php#L75). My current event store contains 1149 aggregates. While replaying the whole eventstream, I get an error from Doctrine about too many open connections.

```
[Doctrine\DBAL\Exception\DriverException]
  An exception occured in driver: SQLSTATE[08004] [1040] Too many connections
```

To avoid this, the `load($id)` method should close the connection right before it returns the `DomainEventStream`.

**Comment by wjzijderveld** [comment]
The DBALEventStore doesn't open it's own connection, so imo it would be weird if it closes the connection, as it would have no way to reopen it when needed.
Do you know why there are even multiple connections opened? Might it be an issue in the service configuration in Laravel?

**Comment by Konafets** [comment]
The DBALEventStore  does not open a connection but `$this->connection->prepare($query)` does it. I added a `$this->connection->close()` to the `load()` method and it worked.

**Comment by ludofleury** [comment]
Does this `$statement->closeCursor();` would also work for your case ?

**Comment by othillo** [comment]
I'm closing this as there is a workaround for this specific problem. A PR to improve the DBALEventStore is always welcome.
