### ISSUE TITLE
Add query to ElasticSearchRepository which allow to fetch only certain fields

### ISSUE THREAD

**Issue by Konafets** [broadway/broadway#259]
All query methods are fetching the whole record from ES and deserialize them into a ReadModel, which is fine in most cases. However, sometimes you need just a subset of the properties. 

My usecase: I present some properties (4 out of 20) of the object via DataTables. At the moment I  manually transform the full object into a format DataTables can handle. This can be avoided by passing the demanded fields to ES and get the raw result back.

**Comment by msvrtan** [comment]
IHMO the idea is to have readmodels that match your business needs...

I would just create another read that has only those 4 properties, actually I'we done similar thing -> having multiple, highly specialized read sides..

**Comment by othillo** [comment]
I'm closing this discussion.
