### ISSUE TITLE
No way to detect race conditions on even stream

### ISSUE THREAD

**Issue by reenl** [broadway/broadway#266]
Hi,

We are working on a system that requires an exclusive lock, before calling an external api. In order to do that we append an event to the store to ensure the process is not performed twice.

However in case of a race condition, the current EventStore throws a generic exception, which is hard to handle, because it can pretty much mean anything at that point, and we have to fall back to string matching.

This is what I propose:
- Add EventStoreException to @throws in DocBlock of EventStore::append (This should already be the case imo)
- Introduce specific exception for race conditions in event store that extends EventStoreException.
- The only regression would be if people catch `DBALEventStoreException` instead of `EventStoreException`.

The question is how should the exception be named, this is what I could think of:
- `DuplicatePlayheadException`
- `EventRaceConditionException`
- `OutdatedAggregateException`

I'm aware of the sensible interface discussion, but I think it should be out of scope for now to prevent an inconsistent base.

If you guys like this I will throw in a PR. Please let me know what class name you prefer.

**Comment by janwalther** [comment]
I would like such an exception as it could also enhance conflict management as described in http://danielwhittaker.me/2014/09/29/handling-concurrency-issues-cqrs-event-sourced-system/ 

With a separate exception one could catch the DuplicatePlayheadException, check if uncommitted events really conflict with other events committed in the meantime and if they do not conflict reassign playheads to avoid exception.

For example when we have a User AR, events like ChangedEmailAddress and ChangedUserName should not trigger a conflict exception as the order of these events does not matter.

Such a conflict resolver would result in much less conflicts in applications where some ARs get written very often.
