### ISSUE TITLE
DBALEventStore::append() can result in an unreleased transaction lock.

### ISSUE THREAD

**Issue by bertramakers** [broadway/broadway#283]
Looking at `DBALEventStore`, the `$id` argument in the `append()` method is checked to see if it can be cast to a string. However it is never again used in that method, so this check is useless. 

https://github.com/broadway/broadway/blob/master/src/Broadway/EventStore/DBALEventStore.php#L103-L108

It seems this check was meant to ensure that the `$id` can be inserted into each row that is appended. However each appended row inserts an id that comes from `DomainMessage::getId()`, using the messages inside the `EventStream`. This id could be completely different than the given `$id`. (Depending on where/how this class is used.)

https://github.com/broadway/broadway/blob/master/src/Broadway/EventStore/DBALEventStore.php#L128

The `DomainMessage::getId()` method could return anything, as its value is not type checked on construction: https://github.com/broadway/broadway/blob/master/src/Broadway/Domain/DomainMessage.php#L53

Seemingly this is not a big issue, as the `insertMessage()` does a type cast to string for this return value: https://github.com/broadway/broadway/blob/master/src/Broadway/EventStore/DBALEventStore.php#L128

However, the `append()` method only catches `DBALException` exceptions, and not the `\Exception` that would be thrown by PHP if the id on the `DomainMessage` is not convertible to a string: https://github.com/broadway/broadway/blob/master/src/Broadway/EventStore/DBALEventStore.php#L118

This in turn would the transaction to not be rolled back, which would probably keep the transaction lock alive for who knows how long.

Proposed solution: Either catch any possible Exception in append(), or use `Connection::transactional($func)` as documented here: http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/transactions.html

**Comment by othillo** [comment]
Yeah, it smells a little bit but it works.

First of all the $id in append() is cast to string to prevent an exception during the transaction later on.
Also the append method when called from the EventSourcedRepository guarantees the aggregate's id to be the same as the id in the domain message, see EventSourcedAggregateRoot::apply().

Since it's not a big issue, I'm leaving it as is. A PR to improve this situation is always welcome.
