### ISSUE TITLE
$id parameter seems to be unnecessary in EventStoreInterface::append()

### ISSUE THREAD

**Issue by bertramakers** [broadway/broadway#284]
Related to #283 , the `append()` method on EventStoreInterface contains an `$id` parameter which seems to be useless as the aggregate id is also present in each `DomainMessage` in the `$eventStream` parameter.

Looking at DBALEventStore, the `$id` parameter is never used. The only code touching it is a type check to see if it can be casted to a string, but as documented in #283 this does not have the intended effect. When inserting the events, the aggregate id on the `DomainMessage` is used instead: https://github.com/broadway/broadway/blob/master/src/Broadway/EventStore/DBALEventStore.php#L128

Looking at InMemoryEventStore, the `$id` parameter is in fact used, but only for initializing a nested array inside the `$events` property: https://github.com/broadway/broadway/blob/master/src/Broadway/EventStore/InMemoryEventStore.php#L49-L51

However in PHP this is not necessary, as it will automatically initialize an array for you when accessing an undefined key or variable as an array, as you can see here: http://sandbox.onlinephpfunctions.com/code/187406b110d9b42377f3d4284fce4d45153ebba2

Either way, even if there was an implementation that would need to use the `$id` parameter, it could get it by accessing the first `DomainMessage` in the `$eventStream` parameter, as each `DomainMessage` also contains the aggregate id.

**Comment by othillo** [comment]
I see your point. The $id in the append method isn't absolutely necessary. 
However in the DBALEventStore it does prevent ugly errors happening inside the transaction.  

Also I'm reluctant to BC break the EventStoreInterface just because of this.
