### ISSUE TITLE
tag 1.0

### ISSUE THREAD

**Issue by othillo** [broadway/broadway#305]
What needs to be done before we can tag 1.0?

- [x] write UPGRADE manual: https://github.com/broadway/broadway/issues/304 https://github.com/broadway/broadway/pull/309
- [x] remove interface suffices: https://github.com/broadway/broadway/issues/12 https://github.com/broadway/broadway/pull/308
- [x] drop elasticsearch-php 1.0: https://github.com/broadway/read-model-elasticsearch/pull/3

After broadway/broadway 1.0 is tagged:
- [x] https://github.com/broadway/event-store-dbal/pull/4
- [x] https://github.com/broadway/broadway-bundle/pull/20
- [x] https://github.com/broadway/read-model-elasticsearch/pull/5
- [x] https://github.com/broadway/broadway-saga/pull/3
- [x] https://github.com/broadway/broadway-sensitive-data/pull/3

**Comment by asm89** [comment]
Only thing left is an "official" release announcement. Working on it. :)

**Comment by unkind** [comment]
#310?
