### ISSUE TITLE
2.0

### ISSUE THREAD

**Issue by othillo** [broadway/broadway#315]
What needs to be done before we can tag 2.0?

- [x] update branch alias: https://github.com/broadway/broadway/pull/316
- [x] use PHP 7's language features: https://github.com/broadway/broadway/pull/317
- [x] drop PHP 5: https://github.com/broadway/broadway/pull/317
- [x] make classes final: https://github.com/broadway/broadway/pull/310
- [x] write UPGRADE manual: https://github.com/broadway/broadway/pull/335
- [x] fix open issues/PR's with BC breaks?
- [x] decide on coding standards: https://github.com/broadway/broadway/pull/320
- [x] apply coding standards: https://github.com/broadway/broadway/pull/329
- [x] do not test HHVM on Travis CI: https://github.com/broadway/broadway/pull/330
- [x] move generic test classes to main namespace: https://github.com/broadway/broadway/pull/327

**Comment by reenl** [comment]
Should/Can we create a 1.1 branch before? Are the coding standards documented?

Technically upgrading to php-7 shouldn't break semver but that might start a war so, I keep that up to you guys.

**Comment by othillo** [comment]
We are going to break BC anyway with the other (open) PR's, so we can avoid the PHP7 semver discussion :)

**Comment by othillo** [comment]
The outdated coding standards are documented in https://github.com/broadway/broadway/blob/master/.php_cs.

I'm thinking about updating them to php-cs-fixer v2 and document them in a different repo.
However, I will not enforce them (besides PSR-2) to not annoy contributors.

**Comment by reenl** [comment]
#320 Upgraded the php_cs file, feel free to decline if not usable :)
