### ISSUE TITLE
No way to interact with Metadata except for serialize

### ISSUE THREAD

**Issue by reenl** [broadway/broadway#318]
I was just wondering if ArrayAccess should be added to Metadata, because there is no way to extract values other than serializing it.

**Comment by othillo** [comment]
I like the fact that the Metadata object is immutable.
Maybe just add a get($key) method?

**Comment by reenl** [comment]
Nice catch, I misread merge. 

Just to get the other options considered:

- Throwing on offsetSet can still enforce immutable, however in this case I prefer get()
- I dislike the need to use serialize on getting all values, I propose also adding values() or all() eventhough serialize would probably do the same.

**Comment by othillo** [comment]
get() and all() sound fine (Symfony ParameterBag style).
PR is welcome ;)

**Comment by othillo** [comment]
fixed by #321
