### ISSUE TITLE
make PHPUnit a dependency

### ISSUE THREAD

**Issue by othillo** [broadway/broadway#341]
currently it is required as a dev dependency, but when you use the test helpers (Testing/) and Criteria objects in your projects you can run into PHPUnit version conflicts. 

This came to light when upgrading to PHPUnit 6.

cc @broadway/broadway

**Comment by UlrichEckhardt** [comment]
You can also suggest something to make clear that you don't have a hard dependency on PHPUnit but that it is required for some additional features.

**Comment by jakubgiminski** [comment]
**Alternative solution: Move the test code away from src.** If I understand correctly, the motivation behind having it there in the first place was to give people some tools to test their things. I think such toolset should be a separate repository (or just let people test their things on their own.)

Also note that the test code in this project follows different styling leaving you with a mix of camel-cased and snake-cased methods in your src, which in my opinion is another reason for moving test code away from there.

**Comment by UlrichEckhardt** [comment]
Rereading what I wrote, I think this link should clarify what I meant: https://getcomposer.org/doc/04-schema.md#suggest.

Concerning the "mix of camel-cased and snake-cased methods", I'd be in favour of refactoring that. It looks like the snake-cased methods could be renamed without breaking things. They are not supposed to be called other than by PHPUnit which will find them using reflection anyway.
