### ISSUE TITLE
test the test helpers with examples

### ISSUE THREAD

**Issue by othillo** [broadway/broadway#345]
I noticed the test helpers in src/*/Testing are vulnerable to change because they are not tested themselves. I suggest creating (tested) examples for them, killing two birds with one stone by also improving the examples/documentation.

**Comment by fritsjanb** [comment]
Was looking at picking this up and noticed that the `CommandHandlerScenarioTestCase` and `AggregateRootScenarioTestCase` are tested through https://github.com/broadway/broadway/tree/master/examples/event-sourced-domain-with-tests

This leaves us with `SerializableEventTestCase` and the read models. Do you still remember for which Testing/* classes you experienced the vulnerable-to-change issues?
