### ISSUE TITLE
Built-in asynchronous way to run processors?

### ISSUE THREAD

**Issue by ivastly** [broadway/broadway#347]
Hello people,

We at VONQ use broadway's Processors for long-runing, complicated things like sending an email or converting a video file. Unfortunetely, Processors are executed in a synchronous way, which is obviously a root of many problems.

Do you think it is a good idea to create a generic broadway's extension/plugin to take care of this? Thus, you would be able to do something like this:
in config:
```yml
SendEmailProcessor:
   async: true
   messaging_provider: broadway.async.rabbitmq
```
in crontab (one line for the entire project):
```bash
* * * * * root project/app/console broadway:async:run # read rabbitmq and run appropriate processors
```

in code:
```php
use Broadway\Processor\AsyncProcessor as AsyncProcessor;
class SendEmailProcessor extends AsyncProcessor {

public handleOrderCompleted() {
 /* send email here */
}
}
```

And the only thing client code implements is the sending email itself. Everything else (create / configure a queue somewhere, put a job with all data in a queue, read a queue and run processors) is done on broadway/async package side.

So, what do you think? Thank you!

**Comment by othillo** [comment]
Hey @biganfa!

When we worked on Broadway at VONQ we just created a RabbitMQProcessor: http://labs.qandidate.com/blog/2015/10/07/asynchronous-event-processing-with-broadway-using-rabbitmq/

Creating a Broadway extension for this is not on our roadmap. Crowdsourced initiatives are welcome, though.

**Comment by matiux** [comment]
Hi @othillo, do you have a concrete example of how you integrated Rabbitmq with Broadway?
Just a snippet of code.

I also wonder if commands or events should be sent in the queue.
Maybe, to say to another microservice **to do something**, send commands could be better?
In this case I could create an async command handler that dispatch command on a rabbitmq queue

What do you think about that?

Thanks
