### ISSUE TITLE
Example/explanation on event sourcing for aggregate roots

### ISSUE THREAD

**Issue by shrikeh** [broadway/broadway#348]
I'm writing a simple CLI-based admin app where the user can update users with roles for given accounts. The intention was that if the user and account combo didn't exist, then running the command to add a role to them automatically created the link. 

This seems to be proving tricky, as all examples explicitly create an entity first, and then add to it. However, from the point of view of this app, creation and update are pretty much the same.

Suggestions on how this could work? I don't really want to have to create separate commands to create when, in a more traditional DB structure, I would just add rows for each account the user now has roles for.

**Comment by wjzijderveld** [comment]
It's difficult to answer this without more information, as I don't know your domain (and it's probably way to late 😳 )

It could be as simple as doing something like this in your aggrate:

```php
// User.php - User aggregate
public function assignRolesForAccount(Account $account, RolesCollection $roles)
{
  $this->linkAccount($account);

  // Some guard here to assure no duplicate/invalid roles are assigned

  $this->apply(new RolesAssignedForAccount($this->id, $account, $roles));
}

public function linkAccount(Account $account)
{
  // Already linked, ignore
  if (in_array($account->getId(), $this->linkedAccounts)) {
    return;
  }

  $this->apply(new AccountLinked($this->id, $account->getId());
}
```

I'll close this for now, but feel free to reopen if you have follow up questions!
