### ISSUE TITLE
What is the overall state of the project? Is it GDPR ready?

### ISSUE THREAD

**Issue by Konafets** [broadway/broadway#352]
Hi

I like to ask about the status of the project? The last commit is from March. 

* Would you (as the owner/maintainer) recommend to use it in an upcoming project? 
* Is the project ready for GDPR or do you planning for it. Here I mean mainly removing data from the event stream after a user request.

Thanks in advance!

**Comment by tonivdv** [comment]
Hi @Konafets ,

> Is the project ready for GDPR or do you planning for it. Here I mean mainly removing data from the event stream after a user request.

I don't see why is this relevant. Broadway comes with tools to do ES. This does not per-se mean privacy stuff. If you are working with privacy data, you'll have to figure out a solution. A nice thread that started around this can be found here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/dddcqrs/IsBqZSLJoiI

> Would you (as the owner/maintainer) recommend to use it in an upcoming project?

Last conference I went, early this year (phpbenelux) I saw a lot of people using this framework in production. So I don't see why you could not use it in upcoming projects?! Last commit is end of March (aka 1month). We can't say it's not maintained ... right ?! 😃 

Cheers

**Comment by wjzijderveld** [comment]
Although there isn't a lot that Broadway could do to provide a plug-and-play GDPR solution, there has been some work done to provide tools you could use: https://github.com/broadway/broadway-sensitive-data
