### ISSUE TITLE
Could you do a new release?

### ISSUE THREAD

**Issue by Lutacon** [broadway/broadway#362]
Last version 2.0.1 is from 16 Dec 2017 and it's 29 commits behind master.

**Comment by UlrichEckhardt** [comment]
It's probably a few more now, including a few bugfixes and support for the new PHP 7.3. Is there anything I could do to help?

**Comment by othillo** [comment]
I just tagged 2.1.0: https://github.com/broadway/broadway/releases/tag/2.1.0
