### ISSUE TITLE
Asymmetry between EventBus interface and EventListener interface

### ISSUE THREAD

**Issue by UlrichEckhardt** [broadway/broadway#371]
I'm just trying to evaluate Broadway and I stumbled across an issue in the `EventBus` interface: You have a `publish()` method there that takes a sequence of `DomainMessage` instances. However, the `EventListener` interface only handles a single `DomainMessage`. Why?

Further questions:
 * Why is there no way to publish a single event? Having to wrap this single event in a redundant `DomainEventStream` is simply unnecessary.
 * The `DomainEventStream` class could use better documentation. In particular, it only (!) really accepts `DomainMessage` instances, because some other code relies on this, so `@param mixed[] $events` is just misleading.
 * Maybe I'm missing something, but what are the requirements on the `DomainMessage` parameters `$id` and `$playhead`? In particular the latter doesn't make sense to me, I would expect the framework to generate the sequence number for me and also to guarantee that these numbers are strictly monotonous.

**Comment by jakubgiminski** [comment]
+1 for the "Further questions" bit.
