### ISSUE TITLE
Processor after projector

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [broadway/broadway#413]
Hi, I would like to know if it's possible to trigger a Processor after the projector in a Symfony application.
In my domain I would like to use a Processor to send notifications, to do this I would like to read from the read model, but if the processor runs before the projector, data are not updated so I am sending old data.

Is it possible to do something about this? 
Thanks

**Comment by othillo** [comment]
I think it would be better if your processor uses data from the event that triggers it. I'm guessing the projector that you want to use first uses the data from this event as well.

**Comment by AlessandroMinoccheri** [comment]
Yeah, thanks @othillo
