### ISSUE TITLE
Aggregator

### ISSUE THREAD

**Issue by renatocosta** [broadway/broadway#419]
Hi,

Is there another way to apply events outside the aggregator?

For example, using an event handler class instead applySomething method.

Best,

**Comment by wjzijderveld** [comment]
The goal of an AggregateRoot is to have a single object that is responsible for the consistency of your entity and possible child entities. This is why the AggregateRoot itself is the one creating and issuing events without allowing external objects to directly add events. 

But maybe I'm misunderstanding your question?

**Comment by renatocosta** [comment]
Thank you for your reply.

I am totally agree.
That was a misunderstanding because I often use Aggregate without event sourcing.
