### ISSUE TITLE
no recent tags?

### ISSUE THREAD

**Issue by federicotorrisi** [broadway/broadway#438]
hello, i noticed that a lot of new features have been developed since your last tag (2.4.0, dated dec. 2020).
some are quite interesting (i've seen there's event upcasting support now) but these are not available on the symfony bundle as it is locked to a specific version and not to dev-master.

are you planning to release a new tag any soon in order to let us use the latest additions?

thanks

**Comment by othillo** [comment]
Thank you, @federicotorrisi, for bringing this to my attention! I just tagged [2.5.0](https://github.com/broadway/broadway/releases/tag/2.5.0)
